package com.paulniu.bill_data_lib.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.paulniu.bill_data_lib.bean.TypeBean;
import com.paulniu.bill_data_lib.bean.BillBean;

import com.paulniu.bill_data_lib.dao.TypeBeanDao;
import com.paulniu.bill_data_lib.dao.BillBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig typeBeanDaoConfig;
    private final DaoConfig billBeanDaoConfig;

    private final TypeBeanDao typeBeanDao;
    private final BillBeanDao billBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        typeBeanDaoConfig = daoConfigMap.get(TypeBeanDao.class).clone();
        typeBeanDaoConfig.initIdentityScope(type);

        billBeanDaoConfig = daoConfigMap.get(BillBeanDao.class).clone();
        billBeanDaoConfig.initIdentityScope(type);

        typeBeanDao = new TypeBeanDao(typeBeanDaoConfig, this);
        billBeanDao = new BillBeanDao(billBeanDaoConfig, this);

        registerDao(TypeBean.class, typeBeanDao);
        registerDao(BillBean.class, billBeanDao);
    }
    
    public void clear() {
        typeBeanDaoConfig.clearIdentityScope();
        billBeanDaoConfig.clearIdentityScope();
    }

    public TypeBeanDao getTypeBeanDao() {
        return typeBeanDao;
    }

    public BillBeanDao getBillBeanDao() {
        return billBeanDao;
    }

}
